// ─────────────────────────────────────────────────────────────────────────────
// AgroWeb — Comprehensive Mock Data Store (India-centric, ₹ pricing)
// ─────────────────────────────────────────────────────────────────────────────

// ── FARMERS ──────────────────────────────────────────────────────────────────
export const mockFarmers = [
  {
    id: "farmer_001",
    name: "Rajesh Patel",
    email: "rajesh@demo.com",
    farmName: "Patel Organic Farms",
    location: "Anand, Gujarat",
    state: "Gujarat",
    avatar: "https://ui-avatars.com/api/?name=Rajesh+Patel&background=16a34a&color=fff",
    rating: 4.9,
    totalProducts: 8,
    joinDate: "2021-04-10",
    certified: true,
    bio: "3rd generation farmer specialising in organic vegetables. Certified by NPOP.",
    totalRevenue: 284700,
    activeListings: 8,
  },
  {
    id: "farmer_002",
    name: "Priya Sharma",
    email: "priya@demo.com",
    farmName: "Sharma Green Fields",
    location: "Nashik, Maharashtra",
    state: "Maharashtra",
    avatar: "https://ui-avatars.com/api/?name=Priya+Sharma&background=0891b2&color=fff",
    rating: 4.7,
    totalProducts: 6,
    joinDate: "2022-01-15",
    certified: true,
    bio: "Specialising in grapes, onions and seasonal fruits in the Nashik valley.",
    totalRevenue: 193500,
    activeListings: 6,
  },
  {
    id: "farmer_003",
    name: "Gurpreet Singh",
    email: "gurpreet@demo.com",
    farmName: "Singh Golden Harvest",
    location: "Ludhiana, Punjab",
    state: "Punjab",
    avatar: "https://ui-avatars.com/api/?name=Gurpreet+Singh&background=b45309&color=fff",
    rating: 4.8,
    totalProducts: 5,
    joinDate: "2020-08-22",
    certified: false,
    bio: "Wheat, paddy and maize farmer with 40 acres in the heart of Punjab.",
    totalRevenue: 412000,
    activeListings: 5,
  },
  {
    id: "farmer_004",
    name: "Kavitha Reddy",
    email: "kavitha@demo.com",
    farmName: "Reddy Spice Gardens",
    location: "Guntur, Andhra Pradesh",
    state: "Andhra Pradesh",
    avatar: "https://ui-avatars.com/api/?name=Kavitha+Reddy&background=dc2626&color=fff",
    rating: 4.6,
    totalProducts: 4,
    joinDate: "2022-06-01",
    certified: true,
    bio: "Renowned for high-quality red chillies and turmeric exported across India.",
    totalRevenue: 156200,
    activeListings: 4,
  },
  {
    id: "farmer_005",
    name: "Suresh Nair",
    email: "suresh@demo.com",
    farmName: "Nair Coconut Estate",
    location: "Thrissur, Kerala",
    state: "Kerala",
    avatar: "https://ui-avatars.com/api/?name=Suresh+Nair&background=7c3aed&color=fff",
    rating: 4.5,
    totalProducts: 5,
    joinDate: "2021-11-08",
    certified: false,
    bio: "Coastal farm producing coconut, banana, and tropical fruits sustainably.",
    totalRevenue: 98400,
    activeListings: 5,
  },
  {
    id: "farmer_006",
    name: "Anita Verma",
    email: "anita@demo.com",
    farmName: "Verma Dairy & Agro",
    location: "Karnal, Haryana",
    state: "Haryana",
    avatar: "https://ui-avatars.com/api/?name=Anita+Verma&background=0f766e&color=fff",
    rating: 4.8,
    totalProducts: 4,
    joinDate: "2020-03-14",
    certified: true,
    bio: "Premium dairy and wheat farm. Our milk products are A2 certified.",
    totalRevenue: 321800,
    activeListings: 4,
  },
]

// ── PRODUCTS ─────────────────────────────────────────────────────────────────
export const mockProducts = [
  // ── Vegetables ──
  {
    id: 1,
    name: "Organic Tomatoes",
    category: "Vegetables",
    price: 42,
    unit: "kg",
    quantity: 500,
    location: "Anand, Gujarat",
    state: "Gujarat",
    image: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=400&h=300&fit=crop",
    farmerName: "Rajesh Patel",
    farmerId: "farmer_001",
    farmerAvatar: "https://ui-avatars.com/api/?name=Rajesh+Patel&background=16a34a&color=fff",
    rating: 4.9,
    reviewCount: 128,
    dateAdded: "2026-08-01",
    organic: true,
    description: "Freshly harvested vine tomatoes, rich in lycopene, no pesticides.",
    harvestDate: "2026-07-28",
    expiryDate: "2026-08-15",
    nutritional: { calories: 18, protein: "0.9g", carbs: "3.9g", fiber: "1.2g" },
  },
  {
    id: 2,
    name: "Fresh Spinach",
    category: "Vegetables",
    price: 35,
    unit: "kg",
    quantity: 200,
    location: "Nashik, Maharashtra",
    state: "Maharashtra",
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=300&fit=crop",
    farmerName: "Priya Sharma",
    farmerId: "farmer_002",
    farmerAvatar: "https://ui-avatars.com/api/?name=Priya+Sharma&background=0891b2&color=fff",
    rating: 4.7,
    reviewCount: 84,
    dateAdded: "2026-08-02",
    organic: true,
    description: "Tender baby spinach, hand-picked at peak nutrition.",
    harvestDate: "2026-07-30",
    expiryDate: "2026-08-10",
    nutritional: { calories: 23, protein: "2.9g", carbs: "3.6g", fiber: "2.2g" },
  },
  {
    id: 3,
    name: "Green Capsicum",
    category: "Vegetables",
    price: 55,
    unit: "kg",
    quantity: 150,
    location: "Anand, Gujarat",
    state: "Gujarat",
    image: "https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?w=400&h=300&fit=crop",
    farmerName: "Rajesh Patel",
    farmerId: "farmer_001",
    farmerAvatar: "https://ui-avatars.com/api/?name=Rajesh+Patel&background=16a34a&color=fff",
    rating: 4.8,
    reviewCount: 56,
    dateAdded: "2026-08-03",
    organic: true,
    description: "Crunchy green capsicum with a mild, sweet flavour. Great for salads.",
    harvestDate: "2026-08-01",
    expiryDate: "2026-08-18",
    nutritional: { calories: 31, protein: "1g", carbs: "6g", fiber: "2.1g" },
  },
  {
    id: 4,
    name: "Purple Onion",
    category: "Vegetables",
    price: 28,
    unit: "kg",
    quantity: 1000,
    location: "Nashik, Maharashtra",
    state: "Maharashtra",
    image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400&h=300&fit=crop",
    farmerName: "Priya Sharma",
    farmerId: "farmer_002",
    farmerAvatar: "https://ui-avatars.com/api/?name=Priya+Sharma&background=0891b2&color=fff",
    rating: 4.6,
    reviewCount: 203,
    dateAdded: "2026-08-04",
    organic: false,
    description: "Premium Nashik onions, bold flavour, long shelf life.",
    harvestDate: "2026-07-20",
    expiryDate: "2026-09-20",
    nutritional: { calories: 40, protein: "1.1g", carbs: "9g", fiber: "1.7g" },
  },
  {
    id: 5,
    name: "Lady Finger (Okra)",
    category: "Vegetables",
    price: 38,
    unit: "kg",
    quantity: 300,
    location: "Guntur, Andhra Pradesh",
    state: "Andhra Pradesh",
    image: "https://images.unsplash.com/photo-1592149613282-d2e7b8f5c278?w=400&h=300&fit=crop",
    farmerName: "Kavitha Reddy",
    farmerId: "farmer_004",
    farmerAvatar: "https://ui-avatars.com/api/?name=Kavitha+Reddy&background=dc2626&color=fff",
    rating: 4.5,
    reviewCount: 47,
    dateAdded: "2026-08-05",
    organic: false,
    description: "Tender, freshly cut okra, ideal for sambar and stir-fries.",
    harvestDate: "2026-08-03",
    expiryDate: "2026-08-12",
    nutritional: { calories: 33, protein: "1.9g", carbs: "7.5g", fiber: "3.2g" },
  },
  // ── Fruits ──
  {
    id: 6,
    name: "Alphonso Mangoes",
    category: "Fruits",
    price: 280,
    unit: "kg",
    quantity: 80,
    location: "Nashik, Maharashtra",
    state: "Maharashtra",
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&h=300&fit=crop",
    farmerName: "Priya Sharma",
    farmerId: "farmer_002",
    farmerAvatar: "https://ui-avatars.com/api/?name=Priya+Sharma&background=0891b2&color=fff",
    rating: 4.9,
    reviewCount: 312,
    dateAdded: "2026-08-01",
    organic: true,
    description: "GI-tagged Alphonso mangoes, the king of mangoes. Rich, creamy, saffron flesh.",
    harvestDate: "2026-07-25",
    expiryDate: "2026-08-10",
    nutritional: { calories: 60, protein: "0.8g", carbs: "15g", fiber: "1.6g" },
  },
  {
    id: 7,
    name: "Bananas (Nendran)",
    category: "Fruits",
    price: 65,
    unit: "kg",
    quantity: 400,
    location: "Thrissur, Kerala",
    state: "Kerala",
    image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=300&fit=crop",
    farmerName: "Suresh Nair",
    farmerId: "farmer_005",
    farmerAvatar: "https://ui-avatars.com/api/?name=Suresh+Nair&background=7c3aed&color=fff",
    rating: 4.7,
    reviewCount: 98,
    dateAdded: "2026-08-03",
    organic: false,
    description: "Kerala Nendran banana — thick, starchy and naturally sweet.",
    harvestDate: "2026-08-01",
    expiryDate: "2026-08-15",
    nutritional: { calories: 89, protein: "1.1g", carbs: "22.8g", fiber: "2.6g" },
  },
  {
    id: 8,
    name: "Pomegranate",
    category: "Fruits",
    price: 120,
    unit: "kg",
    quantity: 200,
    location: "Nashik, Maharashtra",
    state: "Maharashtra",
    image: "https://images.unsplash.com/photo-1541344999736-83eca272f6fc?w=400&h=300&fit=crop",
    farmerName: "Priya Sharma",
    farmerId: "farmer_002",
    farmerAvatar: "https://ui-avatars.com/api/?name=Priya+Sharma&background=0891b2&color=fff",
    rating: 4.8,
    reviewCount: 76,
    dateAdded: "2026-08-02",
    organic: true,
    description: "Ruby-red arils, bursting with antioxidants. Bhagwa variety.",
    harvestDate: "2026-07-28",
    expiryDate: "2026-08-28",
    nutritional: { calories: 83, protein: "1.7g", carbs: "19g", fiber: "4g" },
  },
  {
    id: 9,
    name: "Fresh Coconut",
    category: "Fruits",
    price: 30,
    unit: "piece",
    quantity: 600,
    location: "Thrissur, Kerala",
    state: "Kerala",
    image: "https://images.unsplash.com/photo-1621922898104-b6d4e5e49413?w=400&h=300&fit=crop",
    farmerName: "Suresh Nair",
    farmerId: "farmer_005",
    farmerAvatar: "https://ui-avatars.com/api/?name=Suresh+Nair&background=7c3aed&color=fff",
    rating: 4.5,
    reviewCount: 143,
    dateAdded: "2026-08-04",
    organic: false,
    description: "Tender green coconut, rich in electrolytes, harvested fresh daily.",
    harvestDate: "2026-08-03",
    expiryDate: "2026-08-20",
    nutritional: { calories: 45, protein: "0.5g", carbs: "9.6g", fiber: "0.9g" },
  },
  // ── Grains ──
  {
    id: 10,
    name: "Basmati Rice (Long Grain)",
    category: "Grains",
    price: 95,
    unit: "kg",
    quantity: 2000,
    location: "Karnal, Haryana",
    state: "Haryana",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop",
    farmerName: "Anita Verma",
    farmerId: "farmer_006",
    farmerAvatar: "https://ui-avatars.com/api/?name=Anita+Verma&background=0f766e&color=fff",
    rating: 4.9,
    reviewCount: 287,
    dateAdded: "2026-07-20",
    organic: false,
    description: "Premium Pusa 1121 basmati, extra-long grain, aromatic. Direct mill price.",
    harvestDate: "2026-07-10",
    expiryDate: "2027-07-10",
    nutritional: { calories: 365, protein: "7g", carbs: "80g", fiber: "1.3g" },
  },
  {
    id: 11,
    name: "Sharbati Wheat",
    category: "Grains",
    price: 28,
    unit: "kg",
    quantity: 5000,
    location: "Ludhiana, Punjab",
    state: "Punjab",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=300&fit=crop",
    farmerName: "Gurpreet Singh",
    farmerId: "farmer_003",
    farmerAvatar: "https://ui-avatars.com/api/?name=Gurpreet+Singh&background=b45309&color=fff",
    rating: 4.8,
    reviewCount: 194,
    dateAdded: "2026-07-25",
    organic: false,
    description: "MP Sharbati wheat, soft and sweet, perfect for chapatis and bread.",
    harvestDate: "2026-07-15",
    expiryDate: "2027-07-15",
    nutritional: { calories: 340, protein: "13g", carbs: "72g", fiber: "10g" },
  },
  {
    id: 12,
    name: "Yellow Maize",
    category: "Grains",
    price: 22,
    unit: "kg",
    quantity: 3000,
    location: "Ludhiana, Punjab",
    state: "Punjab",
    image: "https://images.unsplash.com/photo-1601593346740-925612772716?w=400&h=300&fit=crop",
    farmerName: "Gurpreet Singh",
    farmerId: "farmer_003",
    farmerAvatar: "https://ui-avatars.com/api/?name=Gurpreet+Singh&background=b45309&color=fff",
    rating: 4.5,
    reviewCount: 67,
    dateAdded: "2026-08-01",
    organic: false,
    description: "Hybrid yellow maize, ideal for poultry feed, cornflour and snacks.",
    harvestDate: "2026-07-20",
    expiryDate: "2027-01-20",
    nutritional: { calories: 365, protein: "9g", carbs: "74g", fiber: "7g" },
  },
  // ── Dairy ──
  {
    id: 13,
    name: "A2 Cow Milk (Gir Breed)",
    category: "Dairy",
    price: 80,
    unit: "litre",
    quantity: 100,
    location: "Anand, Gujarat",
    state: "Gujarat",
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=300&fit=crop",
    farmerName: "Rajesh Patel",
    farmerId: "farmer_001",
    farmerAvatar: "https://ui-avatars.com/api/?name=Rajesh+Patel&background=16a34a&color=fff",
    rating: 4.9,
    reviewCount: 211,
    dateAdded: "2026-08-09",
    organic: true,
    description: "Pure Gir cow A2 milk. No preservatives, no homogenisation. Daily delivery.",
    harvestDate: "2026-08-09",
    expiryDate: "2026-08-11",
    nutritional: { calories: 61, protein: "3.2g", carbs: "4.8g", fiber: "0g" },
  },
  {
    id: 14,
    name: "Desi Ghee",
    category: "Dairy",
    price: 700,
    unit: "kg",
    quantity: 40,
    location: "Karnal, Haryana",
    state: "Haryana",
    image: "https://images.unsplash.com/photo-1624528167030-5a3a0f32e8c9?w=400&h=300&fit=crop",
    farmerName: "Anita Verma",
    farmerId: "farmer_006",
    farmerAvatar: "https://ui-avatars.com/api/?name=Anita+Verma&background=0f766e&color=fff",
    rating: 4.9,
    reviewCount: 188,
    dateAdded: "2026-07-30",
    organic: true,
    description: "Hand-churned bilona ghee from grass-fed HF cows. Rich, golden, aromatic.",
    harvestDate: "2026-07-28",
    expiryDate: "2027-01-28",
    nutritional: { calories: 900, protein: "0g", carbs: "0g", fiber: "0g" },
  },
  // ── Herbs & Spices ──
  {
    id: 15,
    name: "Fresh Coriander Leaves",
    category: "Herbs",
    price: 20,
    unit: "bundle",
    quantity: 800,
    location: "Anand, Gujarat",
    state: "Gujarat",
    image: "https://images.unsplash.com/photo-1627473673516-2b62d4d6d5aa?w=400&h=300&fit=crop",
    farmerName: "Rajesh Patel",
    farmerId: "farmer_001",
    farmerAvatar: "https://ui-avatars.com/api/?name=Rajesh+Patel&background=16a34a&color=fff",
    rating: 4.7,
    reviewCount: 92,
    dateAdded: "2026-08-08",
    organic: true,
    description: "Fresh, fragrant coriander bundled at farm. No wilting, packed same day.",
    harvestDate: "2026-08-08",
    expiryDate: "2026-08-13",
    nutritional: { calories: 23, protein: "2.1g", carbs: "3.7g", fiber: "2.8g" },
  },
  {
    id: 16,
    name: "Turmeric Powder",
    category: "Spices",
    price: 180,
    unit: "kg",
    quantity: 300,
    location: "Guntur, Andhra Pradesh",
    state: "Andhra Pradesh",
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&h=300&fit=crop",
    farmerName: "Kavitha Reddy",
    farmerId: "farmer_004",
    farmerAvatar: "https://ui-avatars.com/api/?name=Kavitha+Reddy&background=dc2626&color=fff",
    rating: 4.8,
    reviewCount: 156,
    dateAdded: "2026-07-15",
    organic: true,
    description: "Erode turmeric, 3.5% curcumin content. Stone-ground, sun-dried.",
    harvestDate: "2026-06-30",
    expiryDate: "2027-06-30",
    nutritional: { calories: 354, protein: "8g", carbs: "65g", fiber: "21g" },
  },
  {
    id: 17,
    name: "Guntur Red Chilli",
    category: "Spices",
    price: 220,
    unit: "kg",
    quantity: 500,
    location: "Guntur, Andhra Pradesh",
    state: "Andhra Pradesh",
    image: "https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=400&h=300&fit=crop",
    farmerName: "Kavitha Reddy",
    farmerId: "farmer_004",
    farmerAvatar: "https://ui-avatars.com/api/?name=Kavitha+Reddy&background=dc2626&color=fff",
    rating: 4.7,
    reviewCount: 203,
    dateAdded: "2026-07-10",
    organic: false,
    description: "Teja variety, 70,000 SHU Scoville rating. Vibrant red colour.",
    harvestDate: "2026-06-20",
    expiryDate: "2027-06-20",
    nutritional: { calories: 318, protein: "12g", carbs: "56g", fiber: "27g" },
  },
  {
    id: 18,
    name: "Fresh Mint Leaves",
    category: "Herbs",
    price: 15,
    unit: "bundle",
    quantity: 500,
    location: "Nashik, Maharashtra",
    state: "Maharashtra",
    image: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=400&h=300&fit=crop",
    farmerName: "Priya Sharma",
    farmerId: "farmer_002",
    farmerAvatar: "https://ui-avatars.com/api/?name=Priya+Sharma&background=0891b2&color=fff",
    rating: 4.6,
    reviewCount: 61,
    dateAdded: "2026-08-07",
    organic: true,
    description: "Spearmint variety, hand-harvested, intensely aromatic.",
    harvestDate: "2026-08-07",
    expiryDate: "2026-08-12",
    nutritional: { calories: 70, protein: "3.8g", carbs: "14.9g", fiber: "8g" },
  },
  // ── Pulses ──
  {
    id: 19,
    name: "Masoor Dal (Red Lentils)",
    category: "Pulses",
    price: 110,
    unit: "kg",
    quantity: 800,
    location: "Ludhiana, Punjab",
    state: "Punjab",
    image: "https://images.unsplash.com/photo-1585155770447-2f66e2a397b5?w=400&h=300&fit=crop",
    farmerName: "Gurpreet Singh",
    farmerId: "farmer_003",
    farmerAvatar: "https://ui-avatars.com/api/?name=Gurpreet+Singh&background=b45309&color=fff",
    rating: 4.7,
    reviewCount: 134,
    dateAdded: "2026-07-28",
    organic: false,
    description: "Split red lentils, clean and sorted, quick-cooking variety.",
    harvestDate: "2026-07-18",
    expiryDate: "2027-07-18",
    nutritional: { calories: 353, protein: "26g", carbs: "60g", fiber: "11g" },
  },
  {
    id: 20,
    name: "Chana Dal (Bengal Gram)",
    category: "Pulses",
    price: 95,
    unit: "kg",
    quantity: 600,
    location: "Karnal, Haryana",
    state: "Haryana",
    image: "https://images.unsplash.com/photo-1616458561376-c71dbe56abbd?w=400&h=300&fit=crop",
    farmerName: "Anita Verma",
    farmerId: "farmer_006",
    farmerAvatar: "https://ui-avatars.com/api/?name=Anita+Verma&background=0f766e&color=fff",
    rating: 4.6,
    reviewCount: 89,
    dateAdded: "2026-07-22",
    organic: false,
    description: "Hulled and split Bengal gram, high protein, low glycemic index.",
    harvestDate: "2026-07-12",
    expiryDate: "2027-07-12",
    nutritional: { calories: 364, protein: "22g", carbs: "61g", fiber: "17g" },
  },
  // ── More Vegetables ──
  {
    id: 21,
    name: "Brinjal (Eggplant)",
    category: "Vegetables",
    price: 30,
    unit: "kg",
    quantity: 250,
    location: "Thrissur, Kerala",
    state: "Kerala",
    image: "https://images.unsplash.com/photo-1613088433943-88b2a2d4e0b0?w=400&h=300&fit=crop",
    farmerName: "Suresh Nair",
    farmerId: "farmer_005",
    farmerAvatar: "https://ui-avatars.com/api/?name=Suresh+Nair&background=7c3aed&color=fff",
    rating: 4.4,
    reviewCount: 38,
    dateAdded: "2026-08-05",
    organic: false,
    description: "Round Kerala variety brinjal, ideal for curries and roasting.",
    harvestDate: "2026-08-04",
    expiryDate: "2026-08-14",
    nutritional: { calories: 25, protein: "1g", carbs: "6g", fiber: "3g" },
  },
  {
    id: 22,
    name: "Sweet Potato",
    category: "Vegetables",
    price: 45,
    unit: "kg",
    quantity: 400,
    location: "Thrissur, Kerala",
    state: "Kerala",
    image: "https://images.unsplash.com/photo-1596097559565-ecbb7b33cd78?w=400&h=300&fit=crop",
    farmerName: "Suresh Nair",
    farmerId: "farmer_005",
    farmerAvatar: "https://ui-avatars.com/api/?name=Suresh+Nair&background=7c3aed&color=fff",
    rating: 4.6,
    reviewCount: 72,
    dateAdded: "2026-08-03",
    organic: true,
    description: "Orange-flesh sweet potatoes, naturally sweet, dense in beta-carotene.",
    harvestDate: "2026-07-30",
    expiryDate: "2026-09-30",
    nutritional: { calories: 86, protein: "1.6g", carbs: "20g", fiber: "3g" },
  },
  {
    id: 23,
    name: "Bottle Gourd (Lauki)",
    category: "Vegetables",
    price: 22,
    unit: "kg",
    quantity: 350,
    location: "Anand, Gujarat",
    state: "Gujarat",
    image: "https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=400&h=300&fit=crop",
    farmerName: "Rajesh Patel",
    farmerId: "farmer_001",
    farmerAvatar: "https://ui-avatars.com/api/?name=Rajesh+Patel&background=16a34a&color=fff",
    rating: 4.3,
    reviewCount: 44,
    dateAdded: "2026-08-06",
    organic: false,
    description: "Tender young lauki, low-calorie, high water content. Ideal for sabji.",
    harvestDate: "2026-08-05",
    expiryDate: "2026-08-15",
    nutritional: { calories: 15, protein: "0.6g", carbs: "3.4g", fiber: "0.5g" },
  },
  {
    id: 24,
    name: "Garlic",
    category: "Spices",
    price: 150,
    unit: "kg",
    quantity: 200,
    location: "Nashik, Maharashtra",
    state: "Maharashtra",
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=300&fit=crop",
    farmerName: "Priya Sharma",
    farmerId: "farmer_002",
    farmerAvatar: "https://ui-avatars.com/api/?name=Priya+Sharma&background=0891b2&color=fff",
    rating: 4.7,
    reviewCount: 119,
    dateAdded: "2026-07-18",
    organic: false,
    description: "Large clove Nashik garlic, pungent and full-bodied. Excellent shelf life.",
    harvestDate: "2026-07-08",
    expiryDate: "2027-01-08",
    nutritional: { calories: 149, protein: "6.4g", carbs: "33g", fiber: "2.1g" },
  },
]

// ── ORDERS ────────────────────────────────────────────────────────────────────
export const mockOrders = [
  {
    id: "ORD-001",
    buyerId: "buyer_001",
    buyerName: "Amit Kumar",
    farmerId: "farmer_001",
    farmerName: "Rajesh Patel",
    products: [{ id: 1, name: "Organic Tomatoes", quantity: 25, price: 42 }],
    total: 1050,
    status: "delivered",
    orderDate: "2026-08-01",
    deliveryDate: "2026-08-04",
    address: "12 MG Road, Bangalore",
  },
  {
    id: "ORD-002",
    buyerId: "buyer_002",
    buyerName: "Sunita Mehta",
    farmerId: "farmer_002",
    farmerName: "Priya Sharma",
    products: [{ id: 6, name: "Alphonso Mangoes", quantity: 5, price: 280 }],
    total: 1400,
    status: "in_transit",
    orderDate: "2026-08-05",
    deliveryDate: "2026-08-09",
    address: "45 Park Street, Kolkata",
  },
  {
    id: "ORD-003",
    buyerId: "buyer_001",
    buyerName: "Amit Kumar",
    farmerId: "farmer_006",
    farmerName: "Anita Verma",
    products: [
      { id: 10, name: "Basmati Rice", quantity: 10, price: 95 },
      { id: 14, name: "Desi Ghee", quantity: 1, price: 700 },
    ],
    total: 1650,
    status: "confirmed",
    orderDate: "2026-08-07",
    deliveryDate: "2026-08-11",
    address: "12 MG Road, Bangalore",
  },
  {
    id: "ORD-004",
    buyerId: "buyer_003",
    buyerName: "Rohit Jain",
    farmerId: "farmer_004",
    farmerName: "Kavitha Reddy",
    products: [
      { id: 16, name: "Turmeric Powder", quantity: 2, price: 180 },
      { id: 17, name: "Guntur Red Chilli", quantity: 2, price: 220 },
    ],
    total: 800,
    status: "pending",
    orderDate: "2026-08-09",
    deliveryDate: "2026-08-13",
    address: "78 Jubilee Hills, Hyderabad",
  },
  {
    id: "ORD-005",
    buyerId: "buyer_002",
    buyerName: "Sunita Mehta",
    farmerId: "farmer_003",
    farmerName: "Gurpreet Singh",
    products: [{ id: 11, name: "Sharbati Wheat", quantity: 50, price: 28 }],
    total: 1400,
    status: "delivered",
    orderDate: "2026-07-25",
    deliveryDate: "2026-07-29",
    address: "45 Park Street, Kolkata",
  },
  {
    id: "ORD-006",
    buyerId: "buyer_004",
    buyerName: "Deepa Iyer",
    farmerId: "farmer_005",
    farmerName: "Suresh Nair",
    products: [
      { id: 7, name: "Bananas (Nendran)", quantity: 10, price: 65 },
      { id: 9, name: "Fresh Coconut", quantity: 20, price: 30 },
    ],
    total: 1250,
    status: "preparing",
    orderDate: "2026-08-08",
    deliveryDate: "2026-08-12",
    address: "33 T. Nagar, Chennai",
  },
  {
    id: "ORD-007",
    buyerId: "buyer_001",
    buyerName: "Amit Kumar",
    farmerId: "farmer_001",
    farmerName: "Rajesh Patel",
    products: [
      { id: 13, name: "A2 Cow Milk", quantity: 10, price: 80 },
      { id: 15, name: "Fresh Coriander", quantity: 5, price: 20 },
    ],
    total: 900,
    status: "pending",
    orderDate: "2026-08-09",
    deliveryDate: "2026-08-11",
    address: "12 MG Road, Bangalore",
  },
  {
    id: "ORD-008",
    buyerId: "buyer_003",
    buyerName: "Rohit Jain",
    farmerId: "farmer_002",
    farmerName: "Priya Sharma",
    products: [
      { id: 8, name: "Pomegranate", quantity: 5, price: 120 },
      { id: 4, name: "Purple Onion", quantity: 10, price: 28 },
    ],
    total: 880,
    status: "delivered",
    orderDate: "2026-07-30",
    deliveryDate: "2026-08-03",
    address: "78 Jubilee Hills, Hyderabad",
  },
]

// ── WEATHER DATA (8 Indian Cities) ─────────────────────────────────────────
export const mockWeatherData = {
  Delhi: {
    city: "Delhi",
    region: "North",
    current: {
      temperature: 38,
      feelsLike: 43,
      condition: "Hot & Sunny",
      humidity: 45,
      windSpeed: 14,
      uvIndex: 9,
      soilMoisture: "Low (12%)",
      icon: "☀️",
    },
    forecast: [
      { day: "Today", high: 40, low: 28, condition: "Sunny", icon: "☀️", precipitation: 0, farmingTip: "Irrigate early morning; avoid midday watering." },
      { day: "Thu", high: 38, low: 26, condition: "Partly Cloudy", icon: "⛅", precipitation: 5, farmingTip: "Good day for pesticide application — low wind." },
      { day: "Fri", high: 35, low: 24, condition: "Hazy", icon: "🌫️", precipitation: 10, farmingTip: "Monitor wheat crop for heat stress." },
      { day: "Sat", high: 32, low: 22, condition: "Light Rain", icon: "🌦️", precipitation: 60, farmingTip: "Delay fertiliser — rain may wash nutrients." },
      { day: "Sun", high: 30, low: 22, condition: "Cloudy", icon: "☁️", precipitation: 30, farmingTip: "Post-rain: check for fungal diseases." },
    ],
    alerts: [{ type: "heat", message: "Heat wave warning: 40°C expected. Protect tender crops." }],
  },
  Mumbai: {
    city: "Mumbai",
    region: "West",
    current: {
      temperature: 30,
      feelsLike: 36,
      condition: "Humid & Overcast",
      humidity: 88,
      windSpeed: 22,
      uvIndex: 4,
      soilMoisture: "High (72%)",
      icon: "🌧️",
    },
    forecast: [
      { day: "Today", high: 31, low: 26, condition: "Heavy Rain", icon: "🌧️", precipitation: 90, farmingTip: "Ensure drainage channels are clear." },
      { day: "Thu", high: 30, low: 25, condition: "Moderate Rain", icon: "🌦️", precipitation: 70, farmingTip: "Hold off harvesting — produce may rot." },
      { day: "Fri", high: 29, low: 25, condition: "Rainy", icon: "🌧️", precipitation: 80, farmingTip: "Apply fungicide to prevent downy mildew." },
      { day: "Sat", high: 31, low: 24, condition: "Partly Cloudy", icon: "⛅", precipitation: 30, farmingTip: "Good window for harvesting leafy greens." },
      { day: "Sun", high: 32, low: 25, condition: "Overcast", icon: "☁️", precipitation: 50, farmingTip: "Monitor crops for waterlogging damage." },
    ],
    alerts: [{ type: "rain", message: "Heavy monsoon activity. Excess soil moisture risk." }],
  },
  Bangalore: {
    city: "Bangalore",
    region: "South",
    current: {
      temperature: 24,
      feelsLike: 25,
      condition: "Pleasant & Clear",
      humidity: 62,
      windSpeed: 10,
      uvIndex: 6,
      soilMoisture: "Moderate (45%)",
      icon: "⛅",
    },
    forecast: [
      { day: "Today", high: 26, low: 18, condition: "Partly Cloudy", icon: "⛅", precipitation: 15, farmingTip: "Ideal conditions for transplanting seedlings." },
      { day: "Thu", high: 25, low: 17, condition: "Sunny", icon: "☀️", precipitation: 5, farmingTip: "Apply foliar nutrients in the morning." },
      { day: "Fri", high: 23, low: 16, condition: "Light Rain", icon: "🌦️", precipitation: 40, farmingTip: "Natural irrigation — skip watering today." },
      { day: "Sat", high: 22, low: 16, condition: "Cloudy", icon: "☁️", precipitation: 25, farmingTip: "Spray neem oil for pest prevention." },
      { day: "Sun", high: 25, low: 17, condition: "Sunny", icon: "☀️", precipitation: 5, farmingTip: "Perfect day for soil aeration." },
    ],
    alerts: [],
  },
  Pune: {
    city: "Pune",
    region: "West",
    current: {
      temperature: 27,
      feelsLike: 29,
      condition: "Warm with Showers",
      humidity: 74,
      windSpeed: 16,
      uvIndex: 5,
      soilMoisture: "High (65%)",
      icon: "🌦️",
    },
    forecast: [
      { day: "Today", high: 28, low: 21, condition: "Light Rain", icon: "🌦️", precipitation: 55, farmingTip: "Good conditions for onion and grape growth." },
      { day: "Thu", high: 30, low: 22, condition: "Overcast", icon: "☁️", precipitation: 35, farmingTip: "Inspect vines for powdery mildew." },
      { day: "Fri", high: 29, low: 21, condition: "Partly Cloudy", icon: "⛅", precipitation: 20, farmingTip: "Schedule harvesting during sunny windows." },
      { day: "Sat", high: 28, low: 20, condition: "Sunny", icon: "☀️", precipitation: 5, farmingTip: "Excellent day for drying spices outdoors." },
      { day: "Sun", high: 27, low: 20, condition: "Partly Cloudy", icon: "⛅", precipitation: 20, farmingTip: "Fertilise pomegranate orchards today." },
    ],
    alerts: [],
  },
  Ludhiana: {
    city: "Ludhiana",
    region: "North",
    current: {
      temperature: 35,
      feelsLike: 39,
      condition: "Hot & Hazy",
      humidity: 52,
      windSpeed: 18,
      uvIndex: 8,
      soilMoisture: "Low (18%)",
      icon: "🌫️",
    },
    forecast: [
      { day: "Today", high: 37, low: 26, condition: "Sunny", icon: "☀️", precipitation: 2, farmingTip: "Critical irrigation needed for standing crop." },
      { day: "Thu", high: 36, low: 25, condition: "Hot & Sunny", icon: "☀️", precipitation: 0, farmingTip: "Apply mulch to retain soil moisture." },
      { day: "Fri", high: 33, low: 24, condition: "Partly Cloudy", icon: "⛅", precipitation: 10, farmingTip: "Good day for sowing pre-monsoon maize." },
      { day: "Sat", high: 30, low: 22, condition: "Thunderstorm", icon: "⛈️", precipitation: 75, farmingTip: "Secure harvested grains before storm." },
      { day: "Sun", high: 28, low: 21, condition: "Cloudy", icon: "☁️", precipitation: 40, farmingTip: "Post-storm: clear waterlogged fields." },
    ],
    alerts: [{ type: "storm", message: "Thunderstorm expected Saturday. Secure equipment." }],
  },
  Nagpur: {
    city: "Nagpur",
    region: "Central",
    current: {
      temperature: 33,
      feelsLike: 37,
      condition: "Warm & Humid",
      humidity: 68,
      windSpeed: 12,
      uvIndex: 7,
      soilMoisture: "Moderate (38%)",
      icon: "⛅",
    },
    forecast: [
      { day: "Today", high: 34, low: 24, condition: "Partly Cloudy", icon: "⛅", precipitation: 20, farmingTip: "Good conditions for orange harvest." },
      { day: "Thu", high: 36, low: 25, condition: "Sunny", icon: "☀️", precipitation: 5, farmingTip: "Irrigate citrus orchards well today." },
      { day: "Fri", high: 34, low: 24, condition: "Overcast", icon: "☁️", precipitation: 30, farmingTip: "Monitor cotton for bollworm activity." },
      { day: "Sat", high: 31, low: 22, condition: "Light Rain", icon: "🌦️", precipitation: 50, farmingTip: "Natural top-up — reduce irrigation." },
      { day: "Sun", high: 30, low: 22, condition: "Cloudy", icon: "☁️", precipitation: 35, farmingTip: "Good day for soybean transplanting." },
    ],
    alerts: [],
  },
  Hyderabad: {
    city: "Hyderabad",
    region: "South",
    current: {
      temperature: 31,
      feelsLike: 34,
      condition: "Warm & Partly Cloudy",
      humidity: 65,
      windSpeed: 14,
      uvIndex: 7,
      soilMoisture: "Moderate (42%)",
      icon: "⛅",
    },
    forecast: [
      { day: "Today", high: 33, low: 23, condition: "Partly Cloudy", icon: "⛅", precipitation: 20, farmingTip: "Good day for chilli and turmeric inspection." },
      { day: "Thu", high: 32, low: 23, condition: "Overcast", icon: "☁️", precipitation: 30, farmingTip: "Apply potassium fertiliser to chilli crop." },
      { day: "Fri", high: 30, low: 22, condition: "Light Rain", icon: "🌦️", precipitation: 55, farmingTip: "Protect drying spices from rain moisture." },
      { day: "Sat", high: 29, low: 21, condition: "Moderate Rain", icon: "🌧️", precipitation: 70, farmingTip: "Check drainage around turmeric beds." },
      { day: "Sun", high: 31, low: 22, condition: "Partly Cloudy", icon: "⛅", precipitation: 20, farmingTip: "Post-rain soil is ideal for weeding." },
    ],
    alerts: [],
  },
  Jaipur: {
    city: "Jaipur",
    region: "North",
    current: {
      temperature: 36,
      feelsLike: 41,
      condition: "Dry & Hot",
      humidity: 30,
      windSpeed: 20,
      uvIndex: 10,
      soilMoisture: "Very Low (8%)",
      icon: "☀️",
    },
    forecast: [
      { day: "Today", high: 38, low: 28, condition: "Sunny", icon: "☀️", precipitation: 0, farmingTip: "Drip irrigation essential — high evaporation today." },
      { day: "Thu", high: 37, low: 27, condition: "Hot & Sunny", icon: "☀️", precipitation: 0, farmingTip: "Shade nets recommended for vegetable beds." },
      { day: "Fri", high: 35, low: 26, condition: "Partly Cloudy", icon: "⛅", precipitation: 5, farmingTip: "Apply organic mulch to cool soil." },
      { day: "Sat", high: 32, low: 24, condition: "Light Rain", icon: "🌦️", precipitation: 35, farmingTip: "First monsoon shower — excellent sowing timing." },
      { day: "Sun", high: 30, low: 23, condition: "Overcast", icon: "☁️", precipitation: 20, farmingTip: "Sow bajra and jowar if rain continues." },
    ],
    alerts: [{ type: "drought", message: "Dry spell continues. Prioritise water conservation." }],
  },
}

// ── CROP RECOMMENDATION MATRIX ───────────────────────────────────────────────
// Key: `${soilType}_${season}_${region}`
export const cropRecommendationMatrix = {
  // Clay + Summer
  clay_summer_north: [
    { crop: "Paddy (Rice)", emoji: "🌾", confidence: 94, profit: "High", msp: 2183, growingDays: 120, waterNeed: "High", marketDemand: "Very High", tips: ["Keep fields flooded 5–7 cm deep", "Use SRI method for 30% water savings", "Apply zinc sulphate before transplanting"] },
    { crop: "Sugarcane", emoji: "🎋", confidence: 86, profit: "High", msp: 315, growingDays: 365, waterNeed: "High", marketDemand: "High", tips: ["Ratoon crop gives 2nd harvest at low cost", "Use drip irrigation to save 40% water", "Plant trash mulching reduces weed pressure"] },
    { crop: "Cotton", emoji: "🌿", confidence: 78, profit: "Medium", msp: 6620, growingDays: 180, waterNeed: "Medium", marketDemand: "High", tips: ["Choose Bt cotton varieties", "Apply boll protectant at 60 DAS", "Bollworm scouting every 7 days"] },
  ],
  clay_summer_south: [
    { crop: "Paddy (Rice)", emoji: "🌾", confidence: 96, profit: "High", msp: 2183, growingDays: 130, waterNeed: "High", marketDemand: "Very High", tips: ["Samba variety best for South India", "Transplant at 25 days old", "Use Azospirillum biofertiliser"] },
    { crop: "Finger Millet (Ragi)", emoji: "🌾", confidence: 82, profit: "Medium", msp: 3846, growingDays: 90, waterNeed: "Low", marketDemand: "Growing", tips: ["Drought-tolerant — ideal for dry spells", "Rich in calcium; growing urban demand", "Intercrop with groundnut"] },
    { crop: "Groundnut", emoji: "🥜", confidence: 76, profit: "High", msp: 6377, growingDays: 100, waterNeed: "Medium", marketDemand: "High", tips: ["Foliar spray of gypsum at pegging stage", "Intercrop with pearl millet", "Aflatoxin test before selling"] },
  ],
  clay_monsoon_north: [
    { crop: "Paddy (Rice)", emoji: "🌾", confidence: 98, profit: "High", msp: 2183, growingDays: 120, waterNeed: "High", marketDemand: "Very High", tips: ["Monsoon is the best Kharif season for paddy", "Transplanting in flooded fields yields best results", "Watch for blast disease during heavy rains"] },
    { crop: "Maize", emoji: "🌽", confidence: 85, profit: "Medium", msp: 1962, growingDays: 90, waterNeed: "Medium", marketDemand: "High", tips: ["Hybrid seed gives 30% more yield", "Earth-up at knee height for lodging resistance", "Good for poultry feed market"] },
    { crop: "Soybean", emoji: "🌱", confidence: 80, profit: "High", msp: 4300, growingDays: 100, waterNeed: "Medium", marketDemand: "Very High", tips: ["Rhizobium seed treatment mandatory", "Broad-spectrum weedicide at 20 DAS", "No waterlogging — ridge-and-furrow beds"] },
  ],
  clay_winter_north: [
    { crop: "Wheat", emoji: "🌾", confidence: 96, profit: "High", msp: 2275, growingDays: 120, waterNeed: "Medium", marketDemand: "Very High", tips: ["Sow between Nov 1–15 for best yield", "Crown root irrigation at 20–25 DAS", "HD-2967 and PBW-343 are top varieties"] },
    { crop: "Chickpea (Chana)", emoji: "🫘", confidence: 88, profit: "High", msp: 5440, growingDays: 110, waterNeed: "Low", marketDemand: "High", tips: ["Rain-fed crop — minimal irrigation needed", "Use Kabuli variety for export markets", "Wilt-resistant varieties in Punjab"] },
    { crop: "Mustard", emoji: "🌼", confidence: 82, profit: "Medium", msp: 5650, growingDays: 90, waterNeed: "Low", marketDemand: "High", tips: ["Sow by October 15 for best oil content", "Boron application increases seed set", "Good intercrop with wheat"] },
  ],
  // Loam + All seasons
  loam_spring_central: [
    { crop: "Corn (Maize)", emoji: "🌽", confidence: 93, profit: "High", msp: 1962, growingDays: 90, waterNeed: "Medium", marketDemand: "High", tips: ["Best soil type for maize", "Side-dress with urea at knee height", "Detassel for hybrid seed production"] },
    { crop: "Carrot", emoji: "🥕", confidence: 87, profit: "Medium", msp: null, growingDays: 75, waterNeed: "Medium", marketDemand: "High", tips: ["Deep tillage ensures straight roots", "Thin seedlings to 5 cm spacing", "Ooty and Nilgiri varieties command premium"] },
    { crop: "Green Peas", emoji: "🫛", confidence: 81, profit: "High", msp: null, growingDays: 60, waterNeed: "Medium", marketDemand: "High", tips: ["Market before March for best price", "Rhizobium inoculation saves fertiliser", "Pick at 70% fill stage"] },
  ],
  loam_monsoon_west: [
    { crop: "Soybean", emoji: "🌱", confidence: 91, profit: "High", msp: 4300, growingDays: 100, waterNeed: "Medium", marketDemand: "Very High", tips: ["Vidarbha region black loam is ideal", "Seed treatment with Trichoderma prevents root rot", "Market in November for best MSP"] },
    { crop: "Cotton", emoji: "🌿", confidence: 85, profit: "High", msp: 6620, growingDays: 180, waterNeed: "Medium", marketDemand: "High", tips: ["Maharashtra is India's largest cotton producer", "Bt cotton resistant to bollworm", "Harvest in 3 pickings for max quality"] },
    { crop: "Turmeric", emoji: "🟡", confidence: 79, profit: "Very High", msp: null, growingDays: 240, waterNeed: "Medium", marketDemand: "Very High", tips: ["High initial investment — ₹50K/acre cost", "Yield: 25–30 t/ha with good irrigation", "Erode and Sangli are top markets"] },
  ],
  loam_winter_south: [
    { crop: "Tomato", emoji: "🍅", confidence: 92, profit: "High", msp: null, growingDays: 80, waterNeed: "Medium", marketDemand: "Very High", tips: ["Protected cultivation gives 3× yield", "Drip + mulching reduces disease", "Bangalore market pays premium for Grade A"] },
    { crop: "Cabbage", emoji: "🥬", confidence: 85, profit: "Medium", msp: null, growingDays: 70, waterNeed: "Medium", marketDemand: "High", tips: ["Low temperature improves quality", "Transplant 25-day old seedlings", "Good returns when sold directly"] },
    { crop: "Potato", emoji: "🥔", confidence: 78, profit: "High", msp: null, growingDays: 90, waterNeed: "Medium", marketDemand: "Very High", tips: ["Certified seed potato from CPRS Kufri", "Avoid water stress at tuber initiation", "Cold storage near Nilgiris available"] },
  ],
  // Sandy soil
  sandy_summer_east: [
    { crop: "Watermelon", emoji: "🍉", confidence: 88, profit: "High", msp: null, growingDays: 75, waterNeed: "Medium", marketDemand: "High", tips: ["Sandy soil gives best sweetness", "Black mulch increases soil temperature", "Summer demand peaks — good pricing"] },
    { crop: "Groundnut", emoji: "🥜", confidence: 85, profit: "High", msp: 6377, growingDays: 100, waterNeed: "Medium", marketDemand: "High", tips: ["Sandy loam is the ideal groundnut soil", "Harvest when 80% pods are mature", "Andhra Bold variety fetches premium"] },
    { crop: "Sweet Potato", emoji: "🍠", confidence: 76, profit: "Medium", msp: null, growingDays: 110, waterNeed: "Low", marketDemand: "Growing", tips: ["Well-drained sandy soil critical", "Vine cuttings give fastest establishment", "Demand rising in urban health markets"] },
  ],
  sandy_winter_west: [
    { crop: "Cumin (Jeera)", emoji: "🌿", confidence: 90, profit: "Very High", msp: null, growingDays: 100, waterNeed: "Low", marketDemand: "Very High", tips: ["Gujarat/Rajasthan market leader", "Ushira variety most disease-resistant", "1 litre drip water per plant is enough"] },
    { crop: "Fennel (Saunf)", emoji: "🌱", confidence: 82, profit: "High", msp: null, growingDays: 130, waterNeed: "Low", marketDemand: "High", tips: ["Excellent export demand from Gulf", "Sandy soil essential — no waterlogging", "Sow in October for best yield"] },
    { crop: "Wheat", emoji: "🌾", confidence: 75, profit: "Medium", msp: 2275, growingDays: 120, waterNeed: "Medium", marketDemand: "Very High", tips: ["Add organic matter to improve sandy soil", "Rajasthan 4120 variety performs well", "Use surface irrigation sparingly"] },
  ],
  // Silt soil
  silt_monsoon_east: [
    { crop: "Jute", emoji: "🌿", confidence: 91, profit: "Medium", msp: 4500, growingDays: 120, waterNeed: "High", marketDemand: "High", tips: ["West Bengal and Assam silt belt ideal", "Retting in clean water improves fibre", "Government procurement active"] },
    { crop: "Paddy (Rice)", emoji: "🌾", confidence: 87, profit: "High", msp: 2183, growingDays: 130, waterNeed: "High", marketDemand: "Very High", tips: ["Silt-rich delta soil gives high yield", "Bao-dhaan variety for flood-prone areas", "SRI method suitable for silt loam"] },
    { crop: "Mustard", emoji: "🌼", confidence: 80, profit: "Medium", msp: 5650, growingDays: 90, waterNeed: "Low", marketDemand: "High", tips: ["Post-flood silt gives natural fertilisation", "November sowing in East India", "East India mustard commands premium prices"] },
  ],
  // Default fallback
  default: [
    { crop: "Wheat", emoji: "🌾", confidence: 82, profit: "Medium", msp: 2275, growingDays: 120, waterNeed: "Medium", marketDemand: "Very High", tips: ["Widely adaptable across India", "Use certified high-yielding variety seeds", "Government MSP guaranteed"] },
    { crop: "Paddy (Rice)", emoji: "🌾", confidence: 78, profit: "High", msp: 2183, growingDays: 120, waterNeed: "High", marketDemand: "Very High", tips: ["India's most grown crop", "SRI method saves water", "Suitable for most soil types"] },
    { crop: "Maize", emoji: "🌽", confidence: 74, profit: "Medium", msp: 1962, growingDays: 90, waterNeed: "Medium", marketDemand: "High", tips: ["Versatile across climates", "Good for fodder and food processing", "Fast-growing Kharif option"] },
  ],
}

// Helper to get crop recommendations
export const getCropRecommendations = (soilType, season, region, waterAvailability) => {
  const key = `${soilType}_${season}_${region}`
  let recs = cropRecommendationMatrix[key] || cropRecommendationMatrix.default

  // Filter or sort by water availability
  if (waterAvailability === "low") {
    recs = [...recs].sort((a, b) => {
      const order = { Low: 0, Medium: 1, High: 2 }
      return (order[a.waterNeed] || 1) - (order[b.waterNeed] || 1)
    })
  }
  return recs
}

// ── PEST DETECTION LIBRARY ───────────────────────────────────────────────────
export const pestDetectionLibrary = [
  {
    pest: "Aphids (Myzus persicae)",
    emoji: "🦟",
    confidence: 0, // will be randomised
    severity: "Medium",
    cropLoss: "15–25%",
    description: "Tiny soft-bodied insects clustered on new growth and leaf undersides. Secretes honeydew causing sooty mold.",
    symptoms: ["Curling and yellowing of young leaves", "Sticky honeydew residue on leaves", "Black sooty mold on stems"],
    organicTreatment: ["Neem oil spray (5 ml/L) every 3 days", "Reflective mulch repels aphids", "Introduce ladybird beetles as predators"],
    chemicalTreatment: ["Imidacloprid 17.8 SL @ 0.25 ml/L", "Thiamethoxam 25 WG @ 0.3 g/L", "Spray in evening to avoid bee harm"],
    preventionTips: ["Monitor weekly with yellow sticky traps", "Avoid over-nitrogenous fertilization", "Plant marigold as border crop"],
    urgency: "Act within 72 hours",
  },
  {
    pest: "Powdery Mildew (Erysiphe spp.)",
    emoji: "🍄",
    confidence: 0,
    severity: "Medium",
    cropLoss: "20–30%",
    description: "Fungal disease causing white or grey powdery coating on leaves, stems, and fruits. Spreads in dry weather with high humidity.",
    symptoms: ["White powdery patches on leaf surfaces", "Yellowing and browning of affected tissue", "Distorted and stunted new growth"],
    organicTreatment: ["Sulphur dust (20 g/L) spray", "Milk spray (1:9 dilution) weekly", "Potassium bicarbonate @ 5 g/L"],
    chemicalTreatment: ["Hexaconazole 5 SC @ 1 ml/L", "Propiconazole 25 EC @ 0.1%", "Triadimefon 25 WP @ 1 g/L"],
    preventionTips: ["Ensure good air circulation", "Avoid overhead irrigation", "Remove and burn infected plant parts"],
    urgency: "Treat within 5 days",
  },
  {
    pest: "Leaf Blight (Alternaria spp.)",
    emoji: "🍂",
    confidence: 0,
    severity: "High",
    cropLoss: "30–40%",
    description: "Fungal infection causing dark brown spots with concentric rings (target-board pattern) on leaves, spreading rapidly in warm, wet conditions.",
    symptoms: ["Circular brown spots with yellow halos", "Concentric ring pattern on lesions", "Severe defoliation in advanced stage"],
    organicTreatment: ["Copper oxychloride @ 3 g/L", "Trichoderma viride (bioagent) soil drench", "Remove and destroy infected leaves"],
    chemicalTreatment: ["Mancozeb 75 WP @ 2 g/L", "Chlorothalonil 75 WP @ 2 g/L", "Iprodione 50 WP @ 1.5 g/L"],
    preventionTips: ["Use disease-free certified seeds", "Crop rotation of 2–3 years", "Avoid excess nitrogen fertiliser"],
    urgency: "Immediate action required",
  },
  {
    pest: "Whitefly (Bemisia tabaci)",
    emoji: "🦋",
    confidence: 0,
    severity: "High",
    cropLoss: "25–35%",
    description: "Small white-winged insects that suck plant sap and transmit viral diseases. Severe infestations cause plant wilting and crop failure.",
    symptoms: ["White winged insects under leaves", "Yellowing and drying of leaves", "Stunted plant growth; virus-like symptoms"],
    organicTreatment: ["Yellow sticky traps @ 20/acre", "Neem seed kernel extract @ 5%", "Beauveria bassiana biofungicide spray"],
    chemicalTreatment: ["Spiromesifen 22.9 SC @ 0.9 ml/L", "Buprofezin 25 SC @ 1 ml/L", "Do NOT use pyrethroids — whiteflies are resistant"],
    preventionTips: ["Install reflective silver mulch", "Grow sesame as trap crop", "Remove crop debris after harvest"],
    urgency: "Act within 48 hours",
  },
  {
    pest: "Root Rot (Phytophthora spp.)",
    emoji: "🌱",
    confidence: 0,
    severity: "High",
    cropLoss: "40–60%",
    description: "Soil-borne water mold causing root decay and rapid plant death. Spreads through waterlogged conditions and infected soil.",
    symptoms: ["Yellowing and wilting of lower leaves", "Dark brown, rotted root system", "Plant death starting from bottom up"],
    organicTreatment: ["Trichoderma harzianum soil drench", "Improve drainage immediately", "Apply neem cake @ 250 kg/acre"],
    chemicalTreatment: ["Metalaxyl MZ @ 2.5 g/L drenching", "Fosetyl Al @ 2.5 g/L foliar spray", "Raise beds to prevent waterlogging"],
    preventionTips: ["Never plant in waterlogged areas", "Use raised bed cultivation", "Soil solarisation before planting"],
    urgency: "Immediate — remove infected plants",
  },
  {
    pest: "Thrips (Thrips tabaci)",
    emoji: "🐛",
    confidence: 0,
    severity: "Low",
    cropLoss: "10–20%",
    description: "Tiny slender insects that rasp leaf surfaces and feed on cell sap. Cause silvery-white patches and distort flowers.",
    symptoms: ["Silvery-white streaks on leaves", "Distorted and discolored flowers", "Tip burn and leaf curling"],
    organicTreatment: ["Blue sticky traps @ 15/acre", "Spinosad (bio-insecticide) @ 0.5 ml/L", "Garlic extract spray (50 ml/L)"],
    chemicalTreatment: ["Fipronil 5 SC @ 1.5 ml/L", "Emamectin benzoate 5 SG @ 0.4 g/L", "Alternate chemicals to avoid resistance"],
    preventionTips: ["Overhead irrigation disrupts thrips", "Avoid planting near onion fields", "Grow coriander as companion crop"],
    urgency: "Treat within 1 week",
  },
  {
    pest: "Downy Mildew (Peronospora spp.)",
    emoji: "💧",
    confidence: 0,
    severity: "Medium",
    cropLoss: "20–40%",
    description: "Oomycete pathogen thriving in cool, moist conditions. Causes angular yellow patches on leaf tops and grey-purple downy growth beneath.",
    symptoms: ["Angular yellow spots on upper leaf surface", "Grey-purple sporulation on leaf underside", "Rapid progression in humid conditions"],
    organicTreatment: ["Bordeaux mixture (1%) spray", "Avoid overhead irrigation entirely", "Space plants for air circulation"],
    chemicalTreatment: ["Cymoxanil + Mancozeb @ 3 g/L", "Dimethomorph 50 WP @ 1 g/L", "Spray before rain forecast"],
    preventionTips: ["Use resistant varieties where available", "Avoid dense planting", "Morning watering only"],
    urgency: "Treat within 3 days",
  },
  {
    pest: "Stem Borer (Chilo partellus)",
    emoji: "🐝",
    confidence: 0,
    severity: "High",
    cropLoss: "30–50%",
    description: "Larvae bore into stems causing 'dead heart' in young plants and 'white ear' in panicles. Major pest of maize, sorghum and rice.",
    symptoms: ["Dead central shoot (dead heart symptom)", "Circular holes in stem with frass", "White ears in panicle stage"],
    organicTreatment: ["Release Trichogramma chilonis (egg parasitoid)", "Apply NPV (Nuclear Polyhedrosis Virus)", "Napier grass as trap crop border"],
    chemicalTreatment: ["Chlorpyrifos 20 EC @ 2.5 ml/L", "Cartap hydrochloride 4G in stem whorl", "Emamectin benzoate @ 0.4 g/L"],
    preventionTips: ["Synchronised sowing in an area", "Destroy crop stubble after harvest", "Light traps @ 1/acre for adult moths"],
    urgency: "Immediate — check all plants",
  },
]

export const getPestDetectionResult = () => {
  // Randomly select 1–2 pests and assign randomised confidence scores
  const shuffled = [...pestDetectionLibrary].sort(() => Math.random() - 0.5)
  const selected = shuffled.slice(0, Math.random() > 0.5 ? 2 : 1)
  return selected.map((pest, i) => ({
    ...pest,
    confidence: i === 0 ? Math.floor(Math.random() * 10) + 88 : Math.floor(Math.random() * 15) + 70,
  }))
}

// ── DEMO USER ACCOUNTS ────────────────────────────────────────────────────────
export const demoUsers = {
  "farmer@demo.com": {
    id: "farmer_001",
    name: "Rajesh Patel",
    email: "farmer@demo.com",
    role: "farmer",
    farmName: "Patel Organic Farms",
    location: "Anand, Gujarat",
    avatar: "https://ui-avatars.com/api/?name=Rajesh+Patel&background=16a34a&color=fff",
  },
  "buyer@demo.com": {
    id: "buyer_001",
    name: "Amit Kumar",
    email: "buyer@demo.com",
    role: "buyer",
    avatar: "https://ui-avatars.com/api/?name=Amit+Kumar&background=2563eb&color=fff",
  },
}
